/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.Aeropuerto;
import clases.AeropuertoPrivado;
import clases.Avion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidades.MetodosSueltos;
import utilidades.VariablesGlobales;

/**
 *
 * @author Fernando Cuatro
 */
public class AniadirAvion extends javax.swing.JDialog {

 /**
  * Creates new form AniadirAvion
  *
  * @param parent
  * @param modal
  */
 public AniadirAvion(java.awt.Frame parent, boolean modal) {
  super(parent, modal);
  initComponents();

  // Centrar la ventana
  this.setLocationRelativeTo(null);

  // Agregamos a un grupo de botones de forma manual
  this.buttonGroup1.add(this.rdbActivado);
  this.buttonGroup1.add(this.rdbDesactivado);

  // Metodo para cargar los aeropuertos
  // Cargamos los aeropuertos en el comboBox
  MetodosSueltos.cargarAeropuertos(cmbAeropuerto);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  buttonGroup1 = new javax.swing.ButtonGroup();
  jLabel1 = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();
  txtModelo = new javax.swing.JTextField();
  txtxAsientos = new javax.swing.JTextField();
  txtMaxima = new javax.swing.JTextField();
  rdbActivado = new javax.swing.JRadioButton();
  rdbDesactivado = new javax.swing.JRadioButton();
  jLabel4 = new javax.swing.JLabel();
  cmbAeropuerto = new javax.swing.JComboBox<>();
  btnGuardar = new javax.swing.JButton();
  btnCancelar = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

  jLabel1.setText("Modelo:");

  jLabel2.setText("Asientos:");

  jLabel3.setText("Vel. Max:");

  buttonGroup1.add(rdbActivado);
  rdbActivado.setSelected(true);
  rdbActivado.setText("Activado");

  buttonGroup1.add(rdbDesactivado);
  rdbDesactivado.setText("Desactivado");

  jLabel4.setText("Selecciona aeropuerto:");

  btnGuardar.setText("Guardar");
  btnGuardar.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnGuardarActionPerformed(evt);
   }
  });

  btnCancelar.setText("Cancelar");
  btnCancelar.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnCancelarActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGap(107, 107, 107)
      .addComponent(jLabel4))
     .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addGap(80, 80, 80)
        .addComponent(rdbActivado))
       .addGroup(layout.createSequentialGroup()
        .addGap(45, 45, 45)
        .addComponent(jLabel3)))
      .addGap(33, 33, 33)
      .addComponent(rdbDesactivado))
     .addGroup(layout.createSequentialGroup()
      .addGap(45, 45, 45)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(27, 27, 27)
        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
         .addComponent(txtMaxima)
         .addComponent(txtxAsientos, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
         .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
         .addComponent(btnCancelar))
        .addComponent(cmbAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))))
    .addGap(72, 72, 72))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(28, 28, 28)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel1)
     .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(20, 20, 20)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel2)
     .addComponent(txtxAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(19, 19, 19)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel3)
     .addComponent(txtMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(18, 18, 18)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(rdbActivado)
     .addComponent(rdbDesactivado))
    .addGap(16, 16, 16)
    .addComponent(jLabel4)
    .addGap(6, 6, 6)
    .addComponent(cmbAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(btnGuardar)
     .addComponent(btnCancelar))
    .addGap(24, 24, 24))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  // Validaciones adecuadas a gestionar para guardar
  String modelo = this.txtModelo.getText();
  String asientos = this.txtxAsientos.getText();
  String velMax = this.txtMaxima.getText();

  boolean activado = this.rdbActivado.isSelected();

  // Creamos la varibale para gestionar errores
  String errores = "";

  // validaciones
  if (modelo.isEmpty())
  {
   errores += "- El modelo no puede estar vacio\n";
  }

  if (asientos.isEmpty())
  {
   errores += "- Los asientos no pueden estar vacios\n";
  } else
  {
   if (!MetodosSueltos.validaNumeroEntero_Exp(asientos))
   {
    errores += "- El número de asientos no es valido\n";
   }
  }

  if (velMax.isEmpty())
  {
   errores += "- La velocidad no puede quedar vacio\n";
  } else
  {
   if (!MetodosSueltos.validaNumeroReal_Exp(velMax))
   {
    errores += "- La velocidad no tiene un formato validos\n";
   }
  }

  if (errores.isEmpty())
  {

   // Validamos que todo este bien
   int numAsientos = Integer.parseInt(asientos);
   Double velMaxima = Double.parseDouble(velMax);

   // Creamos un avion
   Avion a = new Avion(modelo, numAsientos, velMaxima);

   // Validamos que el avion no exista
   a.setActivado(activado);
   boolean existe = false;

   // Recuperamos el aueropuerto seleccionado
   Aeropuerto auxAero = VariablesGlobales.aeropuertos.get(this.cmbAeropuerto.getSelectedIndex());

   for (Avion aux : auxAero.getAviones())
   {
    if (aux.equals(a))
    {
     existe = true;
    }
   }

   if (!existe)
   {

    try
    {
     // Si no existe agregaremos el avion a el aeropuerto
     auxAero.aniadirAvion(a);

     // Cuando todo este correcto, actualizamos el fichero
     MetodosSueltos.actualizarFichero();

     // Se añadio el avion correctamente
     JOptionPane.showMessageDialog(rootPane, "El avion se agrego correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);

     // Cerramos la ventana despues de completar la accion
     this.dispose();
    } catch (IOException ex)
    {
     Logger.getLogger(AniadirAvion.class.getName()).log(Level.SEVERE, null, ex);
    }

   } else
   {
    JOptionPane.showMessageDialog(rootPane, "El avion ya existe en el aeropuerto", "Error", JOptionPane.ERROR_MESSAGE);
   }

  } else
  {
   JOptionPane.showMessageDialog(rootPane, errores, "Error", JOptionPane.ERROR_MESSAGE);
  }


 }//GEN-LAST:event_btnGuardarActionPerformed

 private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
  // TODO add your handling code here:
  this.dispose();
 }//GEN-LAST:event_btnCancelarActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try
  {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
   {
    if ("Nimbus".equals(info.getName()))
    {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex)
  {
   java.util.logging.Logger.getLogger(AniadirAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex)
  {
   java.util.logging.Logger.getLogger(AniadirAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex)
  {
   java.util.logging.Logger.getLogger(AniadirAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex)
  {
   java.util.logging.Logger.getLogger(AniadirAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the dialog */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    AniadirAvion dialog = new AniadirAvion(new javax.swing.JFrame(), true);
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
     public void windowClosing(java.awt.event.WindowEvent e) {
      System.exit(0);
     }
    });
    dialog.setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton btnCancelar;
 private javax.swing.JButton btnGuardar;
 private javax.swing.ButtonGroup buttonGroup1;
 private javax.swing.JComboBox<String> cmbAeropuerto;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JRadioButton rdbActivado;
 private javax.swing.JRadioButton rdbDesactivado;
 private javax.swing.JTextField txtMaxima;
 private javax.swing.JTextField txtModelo;
 private javax.swing.JTextField txtxAsientos;
 // End of variables declaration//GEN-END:variables
}
