package formularios;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

 /*
  Create una clase llamada VariablesGlobales, donde almacenaremos un 
  ArrayList de Aeropuertos, piensa que modificador debe tener para que 
  pueda ser accesible desde donde queramos.
  */
 public Login() {
  initComponents();

  // Centrar la ventana
  this.setLocationRelativeTo(null);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jLabel4 = new javax.swing.JLabel();
  btnLogin = new javax.swing.JButton();
  btnSalir = new javax.swing.JButton();
  txtNombre = new javax.swing.JTextField();
  txtPass = new javax.swing.JPasswordField();
  jLabel1 = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();
  jLabel5 = new javax.swing.JLabel();

  jLabel4.setFont(new java.awt.Font("Gotham", 1, 36)); // NOI18N
  jLabel4.setForeground(new java.awt.Color(238, 238, 238));
  jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel4.setText("Iniciar sesión");
  jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("¡Bienvenidos!");
  setResizable(false);

  btnLogin.setText("Comenzar");
  btnLogin.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnLoginActionPerformed(evt);
   }
  });

  btnSalir.setText("Salir");
  btnSalir.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnSalirActionPerformed(evt);
   }
  });

  jLabel1.setText("Contraseña");

  jLabel3.setText("Nombre");

  jLabel5.setFont(new java.awt.Font("Gotham", 1, 36)); // NOI18N
  jLabel5.setForeground(new java.awt.Color(238, 238, 238));
  jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel5.setText("Iniciar sesión");
  jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(23, 23, 23)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel3)
         .addComponent(jLabel1)
         .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 17, Short.MAX_VALUE)))
      .addContainerGap())
     .addGroup(layout.createSequentialGroup()
      .addComponent(btnLogin)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(25, 25, 25))
     .addGroup(layout.createSequentialGroup()
      .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(22, 22, 22)
    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jLabel3)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addGap(18, 18, 18)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(btnLogin)
     .addComponent(btnSalir))
    .addContainerGap(22, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

     System.exit(0);

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

     String nombre = this.txtNombre.getText();
     String pass = this.txtPass.getText();

     if (nombre.equals("admin") && pass.equals("admin"))
     {
      Principal ventana = new Principal();
      ventana.setVisible(true);
      this.dispose();
     } else
     {
      JOptionPane.showMessageDialog(this,
              "Credenciales erroneas",
              "Error",
              JOptionPane.ERROR_MESSAGE);
     }


    }//GEN-LAST:event_btnLoginActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try
  {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
   {
    if ("Nimbus".equals(info.getName()))
    {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex)
  {
   java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex)
  {
   java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex)
  {
   java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex)
  {
   java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new Login().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton btnLogin;
 private javax.swing.JButton btnSalir;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JTextField txtNombre;
 private javax.swing.JPasswordField txtPass;
 // End of variables declaration//GEN-END:variables
}
