/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Aeropuerto;
import clases.AeropuertoPublico;
import clases.AeropuertoPrivado;
import clases.Direccion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidades.MetodosSueltos;

/**
 *
 * @author Fernando Cuatro
 */
public class AniadirAeropuerto extends javax.swing.JDialog {

 /**
  * Creates new form AniadirAeropuerto
  * @param parent
  * @param modal
  */
 public AniadirAeropuerto(java.awt.Frame parent, boolean modal) {
  super(parent, modal);
  initComponents();
  
  // Para central el modal
  this.setLocationRelativeTo(null);
  
  // Hacer que se seleccione un radiobutton u otro pero no los dos
  this.buttonGroup1.add(this.rdoPrivado);
  this.buttonGroup1.add(this.rdoPublico);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  buttonGroup1 = new javax.swing.ButtonGroup();
  jLabel1 = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  txtNombre = new javax.swing.JTextField();
  jLabel3 = new javax.swing.JLabel();
  txtPais = new javax.swing.JTextField();
  jLabel4 = new javax.swing.JLabel();
  txtCalle = new javax.swing.JTextField();
  jLabel5 = new javax.swing.JLabel();
  txtCuidad = new javax.swing.JTextField();
  jLabel6 = new javax.swing.JLabel();
  jLabel7 = new javax.swing.JLabel();
  txtInaguracion = new javax.swing.JTextField();
  txtNumero = new javax.swing.JTextField();
  jLabel8 = new javax.swing.JLabel();
  txtCapacidad = new javax.swing.JTextField();
  rdoPublico = new javax.swing.JRadioButton();
  jLabel9 = new javax.swing.JLabel();
  txtFinanciacion = new javax.swing.JTextField();
  jLabel10 = new javax.swing.JLabel();
  txtDiscapacidad = new javax.swing.JTextField();
  rdoPrivado = new javax.swing.JRadioButton();
  jLabel11 = new javax.swing.JLabel();
  txtNumeroSocios = new javax.swing.JTextField();
  btnCancelar = new javax.swing.JButton();
  btnGuardar = new javax.swing.JButton();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

  jLabel1.setFont(new java.awt.Font("Gotham", 1, 24)); // NOI18N
  jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel1.setText("Añadir un nuevo aeropuerto");

  jLabel2.setText("Nombre: ");

  jLabel3.setText("País:");

  jLabel4.setText("Calle:");

  jLabel5.setText("Cuidad:");

  jLabel6.setText("Número:");

  jLabel7.setText("Año inaguración:");

  jLabel8.setText("Capacidad:");

  rdoPublico.setSelected(true);
  rdoPublico.setText("Público");
  rdoPublico.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    rdoPublicoActionPerformed(evt);
   }
  });

  jLabel9.setText("Financiación:");

  jLabel10.setText("Discapacitados:");

  rdoPrivado.setText("Privado");
  rdoPrivado.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    rdoPrivadoActionPerformed(evt);
   }
  });

  jLabel11.setText("Numero de socios:");

  txtNumeroSocios.setEnabled(false);

  btnCancelar.setText("Cerrar");
  btnCancelar.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnCancelarActionPerformed(evt);
   }
  });

  btnGuardar.setText("Guardar");
  btnGuardar.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnGuardarActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGap(20, 20, 20)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addComponent(jLabel2)
        .addGap(9, 9, 9)
        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(66, 66, 66)
        .addComponent(jLabel3)
        .addGap(6, 6, 6)
        .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
       .addGroup(layout.createSequentialGroup()
        .addGap(8, 8, 8)
        .addComponent(jLabel1))))
     .addGroup(layout.createSequentialGroup()
      .addGap(40, 40, 40)
      .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(0, 0, 0)
      .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(50, 50, 50)
      .addComponent(jLabel5)
      .addGap(8, 8, 8)
      .addComponent(txtCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGap(20, 20, 20)
      .addComponent(jLabel6)
      .addGap(12, 12, 12)
      .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(20, 20, 20)
      .addComponent(jLabel7)
      .addGap(5, 5, 5)
      .addComponent(txtInaguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(30, 30, 30)
      .addComponent(jLabel8)
      .addGap(7, 7, 7)
      .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGap(20, 20, 20)
      .addComponent(rdoPublico))
     .addGroup(layout.createSequentialGroup()
      .addGap(30, 30, 30)
      .addComponent(jLabel9)
      .addGap(6, 6, 6)
      .addComponent(txtFinanciacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(30, 30, 30)
      .addComponent(jLabel10)
      .addGap(9, 9, 9)
      .addComponent(txtDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGap(20, 20, 20)
      .addComponent(rdoPrivado))
     .addGroup(layout.createSequentialGroup()
      .addGap(30, 30, 30)
      .addComponent(jLabel11)
      .addGap(14, 14, 14)
      .addComponent(txtNumeroSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGap(330, 330, 330)
      .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(7, 7, 7)
      .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addContainerGap(26, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGap(70, 70, 70)
      .addComponent(jLabel2))
     .addGroup(layout.createSequentialGroup()
      .addGap(60, 60, 60)
      .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGap(68, 68, 68)
      .addComponent(jLabel3))
     .addGroup(layout.createSequentialGroup()
      .addGap(60, 60, 60)
      .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(14, 14, 14)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(txtCuidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(layout.createSequentialGroup()
      .addGap(10, 10, 10)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel4)
       .addComponent(jLabel5))))
    .addGap(14, 14, 14)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(txtInaguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(layout.createSequentialGroup()
      .addGap(10, 10, 10)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel6)
       .addComponent(jLabel7)
       .addComponent(jLabel8))))
    .addGap(24, 24, 24)
    .addComponent(rdoPublico)
    .addGap(2, 2, 2)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(txtFinanciacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(txtDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addGroup(layout.createSequentialGroup()
      .addGap(10, 10, 10)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel9)
       .addComponent(jLabel10))))
    .addGap(24, 24, 24)
    .addComponent(rdoPrivado)
    .addGap(2, 2, 2)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGap(10, 10, 10)
      .addComponent(jLabel11))
     .addComponent(txtNumeroSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    .addGap(4, 4, 4)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(btnGuardar)
     .addComponent(btnCancelar))
    .addContainerGap(16, Short.MAX_VALUE))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  // Contenedor de errores
  String errores = "";
  
  // Variables para recoger los valores
  String nombre = this.txtNombre.getText();
  String pais = this.txtPais.getText();
  String calle = this.txtCalle.getText();
  String numero = this.txtNumero.getText();
  String cuidad = this.txtCuidad.getText();
  String anioInaguracion = this.txtInaguracion.getText();
  String capacidad = this.txtCapacidad.getText();
  
  String financiacion = "", discapacitados = "", numSocios = "";
  
  // Validar que todos los archivos esten llenos
  if (nombre.isEmpty())
  {
   errores += "- El nombre no puede estar vacio \n";
  }
  
  if (pais.isEmpty())
  {
   errores += "- El pais no puede estar vacio \n";
  }
  
  if (calle.isEmpty())
  {
   errores += "- La calle no puede estar vacia \n";
  }
  
  if (cuidad.isEmpty())
  {
   errores += "- La cuidad no puede estar vacia \n";
  }
  
  // Validar enteros
  if (numero.isEmpty())
  {
   errores += "- El numero no puede estar vacio \n";
  } else {
   // Negamos, que nos mande cuando no sea numero
   if (!MetodosSueltos.validaNumeroEntero_Exp(numero))
   {
    errores += "- El numero no es un formato valido \n";
   }
  }
  
  if (capacidad.isEmpty())
  {
   errores += "- La capacidad no puede estar vacia \n";
  } else {
   // Negamos, que nos mande cuando no sea numero
   if (!MetodosSueltos.validaNumeroReal_Exp(capacidad))
   {
    errores += "- La capacidad no tiene un formato valido \n";
   }
  }
  
  if (anioInaguracion.isEmpty())
  {
   errores += "- El año de inaguracion no puede estar vacio \n";
  } else {
   // Negamos, que nos mande cuando no sea numero
   if (!MetodosSueltos.validaNumeroEntero_Exp(anioInaguracion))
   {
    errores += "- El año de inaguracion no tiene un formato valido \n";
   }
  }
  
  // Validar por medio de que el radiobuttom este seleccionado
  if (this.rdoPublico.isSelected())
  {
   financiacion = this.txtFinanciacion.getText();
   discapacitados = this.txtDiscapacidad.getText();
   
   // Tenemos que validar que financiacnion y descapacitados, no este vacio
   if (financiacion.isEmpty())
   {
    errores += "- La financiación no puede estar vacia \n";
   } else {
    // Negamos, que nos mande cuando no sea numero
    if (!MetodosSueltos.validaNumeroReal_Exp(financiacion))
    {
     errores += "- La financiación no tiene un formato valido \n";
    }
   }
  
   if (discapacitados.isEmpty())
   {
    errores += "- Los discapacitados no pueden estar vacios \n";
   } else {
    // Negamos, que nos mande cuando no sea numero
    if (!MetodosSueltos.validaNumeroEntero_Exp(discapacitados))
    {
     errores += "- Los discapacitados no tienen un formato valido \n";
    }
   }
   
  }
  
  if (this.rdoPrivado.isSelected())
  {
   numSocios = this.txtNumeroSocios.getText();
   
   // Tenemos que validar que numero de socios, no este vacio
   if (numSocios.isEmpty())
   {
    errores += "- Los numeros de socios no pueden estar vacios \n";
   } else {
    // Negamos, que nos mande cuando no sea numero
    if (!MetodosSueltos.validaNumeroEntero_Exp(numSocios))
    {
     errores += "- Los numeros de socios no tienen un formato valido \n";
    }
   }
  }
  
  if (errores.isEmpty())
  {
   // Si ya sabemos que esta todo bien, hacemos las configuraciones correspondientes
   int numeroAeropuerto = Integer.parseInt(numero);
   int anioInaguracionAeropuerto = Integer.parseInt(anioInaguracion);
   int capacidadAeropuerto = Integer.parseInt(capacidad);
   
   // Creamos un aeropuerto, para despues configurarlo
   Aeropuerto aux;
   // Enviamos la direccion al objeto de la direccion
   Direccion dir = new Direccion(pais, calle, numeroAeropuerto, cuidad);
   
   if (this.rdoPublico.isSelected())
   {
    double financiacionAeropuerto = Double.parseDouble(financiacion);
    int discapacitadosAeropuerto = Integer.parseInt(discapacitados);
    
    // Creamos un aeropuerto publico
    aux = new AeropuertoPublico(financiacionAeropuerto, discapacitadosAeropuerto, nombre, dir, anioInaguracionAeropuerto, capacidadAeropuerto);
    
   } else
   {
    int numSociosAeropuerto = Integer.parseInt(numSocios);
    
    // Creamos un aeropuerto privado
    aux = new AeropuertoPrivado(numSociosAeropuerto, nombre, dir, anioInaguracionAeropuerto, capacidadAeropuerto);
     
   }
   
   try
   {
    MetodosSueltos.escribirAeropuerto(aux);
    
    JOptionPane.showMessageDialog(this, "Aeropuerto añadidio correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
   } catch (Exception ex)
   {
    System.out.println("añadirAeropuerto.java | +info: " + ex.getMessage());
   }
   
  } else {
   JOptionPane.showMessageDialog(this, errores, "Error", JOptionPane.ERROR_MESSAGE);
  }
  
 }//GEN-LAST:event_btnGuardarActionPerformed

 private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
  // Cerrar el Jdialog
  this.dispose();
 }//GEN-LAST:event_btnCancelarActionPerformed

 private void rdoPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPublicoActionPerformed
 
  // Desabilitar
  this.txtFinanciacion.setEnabled(true);
  this.txtDiscapacidad.setEnabled(true);
  this.txtNumeroSocios.setEnabled(false);
  this.txtNumeroSocios.setText("");
 }//GEN-LAST:event_rdoPublicoActionPerformed

 private void rdoPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPrivadoActionPerformed
  
  // Desabilitar
  this.txtFinanciacion.setEnabled(false);
  this.txtDiscapacidad.setEnabled(false);
  this.txtNumeroSocios.setEnabled(true);
  this.txtFinanciacion.setText("");
  this.txtDiscapacidad.setText("");
 }//GEN-LAST:event_rdoPrivadoActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton btnCancelar;
 private javax.swing.JButton btnGuardar;
 private javax.swing.ButtonGroup buttonGroup1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel10;
 private javax.swing.JLabel jLabel11;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JLabel jLabel7;
 private javax.swing.JLabel jLabel8;
 private javax.swing.JLabel jLabel9;
 private javax.swing.JRadioButton rdoPrivado;
 private javax.swing.JRadioButton rdoPublico;
 private javax.swing.JTextField txtCalle;
 private javax.swing.JTextField txtCapacidad;
 private javax.swing.JTextField txtCuidad;
 private javax.swing.JTextField txtDiscapacidad;
 private javax.swing.JTextField txtFinanciacion;
 private javax.swing.JTextField txtInaguracion;
 private javax.swing.JTextField txtNombre;
 private javax.swing.JTextField txtNumero;
 private javax.swing.JTextField txtNumeroSocios;
 private javax.swing.JTextField txtPais;
 // End of variables declaration//GEN-END:variables
}
