/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Cuatro
 */
public class login extends javax.swing.JFrame {

 /**
  * Creates new form login
  */
 public login() {
  initComponents();
  
  // Centrar la ventana al iniciarla
  this.setLocationRelativeTo(null);
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  btnLogin = new javax.swing.JButton();
  btnSalir = new javax.swing.JButton();
  txtNombre = new javax.swing.JTextField();
  txtPass = new javax.swing.JPasswordField();
  jLabel1 = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("¡Bienvenidos!");

  btnLogin.setText("Comenzar");
  btnLogin.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnLoginActionPerformed(evt);
   }
  });

  btnSalir.setText("Salir");
  btnSalir.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    btnSalirActionPerformed(evt);
   }
  });

  jLabel1.setText("Usuario:");

  jLabel2.setText("Contraseña:");

  jLabel3.setFont(new java.awt.Font("Gotham", 1, 36)); // NOI18N
  jLabel3.setForeground(new java.awt.Color(238, 238, 238));
  jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
  jLabel3.setText("Iniciar sesión");
  jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(62, 62, 62)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addComponent(jLabel1)
     .addComponent(txtPass)
     .addGroup(layout.createSequentialGroup()
      .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addGap(87, 87, 87)
      .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addComponent(jLabel2)
     .addComponent(txtNombre)
     .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap(67, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(23, 23, 23)
    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jLabel2)
    .addGap(6, 6, 6)
    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(btnSalir)
     .addComponent(btnLogin))
    .addGap(22, 22, 22))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
  // Cerramos el programa por completo
  System.exit(0);
 }//GEN-LAST:event_btnSalirActionPerformed

 private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
  // Recoger el contenido de la variable
  String nombre = this.txtNombre.getText();
  String pass = this.txtPass.getText();
  
  if (nombre.equals("admin") && pass.equals("admin"))
  {
   // Creamos un objeto para abrir una nueva ventana
   Principal principal = new Principal();
   // Mostramos la ventana
   principal.setVisible(true);
   
   // Cerramos la ventana que corresponde a la de Login para dejar 
   // abierta la principal
   this.dispose();
  } else
  {
   // Mostramos un mensaje de alerta
   // 1. Hacemos referencia al formulario
   // 2. Es el mensaje a mostrar
   // 3. El titulo de la ventana
   // 4. El tipo del icono que se mostrara
   
   JOptionPane.showMessageDialog(this, "Los datos no son correctos", "Error", JOptionPane.ERROR_MESSAGE);
  }
 }//GEN-LAST:event_btnLoginActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try
  {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
   {
    if ("Nimbus".equals(info.getName()))
    {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex)
  {
   java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex)
  {
   java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex)
  {
   java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex)
  {
   java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new login().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton btnLogin;
 private javax.swing.JButton btnSalir;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JTextField txtNombre;
 private javax.swing.JPasswordField txtPass;
 // End of variables declaration//GEN-END:variables
}
