/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clases.Aeropuerto;
import javax.swing.table.DefaultTableModel;
import utilidades.MetodosSueltos;
import utilidades.VariablesGlobales;

/**
 *
 * @author Fernando Cuatro
 */
public class Principal extends javax.swing.JFrame {

 /*
 En nuestra ventana Principal, añadiremos un menu con las siguientes opciones:
 
 (...) Signfica que se hara abrira una nueva ventana
 
 Aeropuertos 
  > Añadir...
  > Editar...
  > Borrar
  > Ganancias
  > Mostrar informacion
 
 Aviones
  > Añadir...
  > Activar / Desactivar avion...
  > Borrar...
 
 Salir
 
 */
 
 
 /**
  * Creates new form Principal
  */
 public Principal() {
  initComponents();
  this.setLocationRelativeTo(null);
  
  // Leemos la informacion de los aeropuertos
  // del fichero de la lista
  MetodosSueltos.leerAeropuertos();
  this.cargarDatos();
 }
 
 // Configuracion para la tabla
 private DefaultTableModel modeloTabla;
 
 // Metodo para cargar datos
 public void cargarDatos() {
  
  // Esto permite que no se puedan editar las celdas
  this.modeloTabla = new DefaultTableModel() {
   @Override
   public boolean isCellEditable(int row, int column) {
    return false;
   }
  };
  
  // los Jtable, vienen a pedazos, tenemos que hacerlo manualmente
  this.tblAeropuertos.setModel(modeloTabla);
  
  // Agregamos las columnas
  modeloTabla.addColumn("id");
  this.tblAeropuertos.getColumnModel().getColumn(0).setPreferredWidth(15);
  modeloTabla.addColumn("Nombre");
  modeloTabla.addColumn("Pais");
  modeloTabla.addColumn("Numero");
  modeloTabla.addColumn("Calle");
  modeloTabla.addColumn("Cuidad");
  modeloTabla.addColumn("Inaguracion");
  modeloTabla.addColumn("Capacidad");
  
  // recorremos los aeropuertos
  Object[] fila;
  
  for (Aeropuerto aux:VariablesGlobales.aeropuertos)
  {
   fila = new Object[8];
   
   fila[0] = aux.getId();
   fila[1] = aux.getNombre();
   fila[2] = aux.getDireccion().getPais();
   fila[3] = aux.getDireccion().getNumero();
   fila[4] = aux.getDireccion().getCalle();
   fila[5] = aux.getDireccion().getCiudad();
   fila[6] = aux.getAnioInauguracion();
   fila[7] = aux.getCapacidad();
   
   modeloTabla.addRow(fila); 
  }
          
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jScrollPane1 = new javax.swing.JScrollPane();
  tblAeropuertos = new javax.swing.JTable();
  jMenuBar1 = new javax.swing.JMenuBar();
  jMenu3 = new javax.swing.JMenu();
  mitAeropuertoAniadir = new javax.swing.JMenuItem();
  mitAeropuertoEditar = new javax.swing.JMenuItem();
  mitAeropuertoBorrar = new javax.swing.JMenuItem();
  mitAeropuertoGanancias = new javax.swing.JMenuItem();
  mitAeropuertoInformacion = new javax.swing.JMenuItem();
  jMenu1 = new javax.swing.JMenu();
  mitAvionesAniadir = new javax.swing.JMenuItem();
  mitAvionesOnOff = new javax.swing.JMenuItem();
  mitAvionesBorrar = new javax.swing.JMenuItem();
  jMenu2 = new javax.swing.JMenu();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  tblAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
   new Object [][] {
    {null, null, null, null},
    {null, null, null, null},
    {null, null, null, null},
    {null, null, null, null}
   },
   new String [] {
    "Title 1", "Title 2", "Title 3", "Title 4"
   }
  ));
  jScrollPane1.setViewportView(tblAeropuertos);

  jMenu3.setText("Aeropuertos");

  mitAeropuertoAniadir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
  mitAeropuertoAniadir.setText("Añadir..");
  mitAeropuertoAniadir.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    mitAeropuertoAniadirActionPerformed(evt);
   }
  });
  jMenu3.add(mitAeropuertoAniadir);

  mitAeropuertoEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
  mitAeropuertoEditar.setText("Editar...");
  jMenu3.add(mitAeropuertoEditar);

  mitAeropuertoBorrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
  mitAeropuertoBorrar.setText("Borrar");
  jMenu3.add(mitAeropuertoBorrar);

  mitAeropuertoGanancias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
  mitAeropuertoGanancias.setText("Ganancias");
  jMenu3.add(mitAeropuertoGanancias);

  mitAeropuertoInformacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_EQUALS, java.awt.event.InputEvent.CTRL_MASK));
  mitAeropuertoInformacion.setText("Mostrar información");
  jMenu3.add(mitAeropuertoInformacion);

  jMenuBar1.add(jMenu3);

  jMenu1.setText("Aviones");

  mitAvionesAniadir.setText("Añadir...");
  jMenu1.add(mitAvionesAniadir);

  mitAvionesOnOff.setText("Activar / Desactivar");
  jMenu1.add(mitAvionesOnOff);

  mitAvionesBorrar.setText("Borrar");
  jMenu1.add(mitAvionesBorrar);

  jMenuBar1.add(jMenu1);

  jMenu2.setText("Salir");
  jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
   public void mouseClicked(java.awt.event.MouseEvent evt) {
    jMenu2MouseClicked(evt);
   }
  });
  jMenuBar1.add(jMenu2);

  setJMenuBar(jMenuBar1);

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
    .addContainerGap())
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    .addContainerGap(7, Short.MAX_VALUE)
    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap())
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
  // Cerrar nuestro programa
  System.exit(0);
 }//GEN-LAST:event_jMenu2MouseClicked

 private void mitAeropuertoAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAeropuertoAniadirActionPerformed
  // Abrir la opcion de añadir aeropuerto
  
  // El this hace referencia al padre => principal es el padre
  // El true si es modal o no es modal, hasta que yo no termine; no me dejaria hacer otra cosa
  AniadirAeropuerto ventana = new AniadirAeropuerto(this, true);
  ventana.setVisible(true);
   this.cargarDatos();
 }//GEN-LAST:event_mitAeropuertoAniadirActionPerformed


 // El consejo es dejarle el main al unico que empiece

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JMenu jMenu1;
 private javax.swing.JMenu jMenu2;
 private javax.swing.JMenu jMenu3;
 private javax.swing.JMenuBar jMenuBar1;
 private javax.swing.JScrollPane jScrollPane1;
 private javax.swing.JMenuItem mitAeropuertoAniadir;
 private javax.swing.JMenuItem mitAeropuertoBorrar;
 private javax.swing.JMenuItem mitAeropuertoEditar;
 private javax.swing.JMenuItem mitAeropuertoGanancias;
 private javax.swing.JMenuItem mitAeropuertoInformacion;
 private javax.swing.JMenuItem mitAvionesAniadir;
 private javax.swing.JMenuItem mitAvionesBorrar;
 private javax.swing.JMenuItem mitAvionesOnOff;
 private javax.swing.JTable tblAeropuertos;
 // End of variables declaration//GEN-END:variables
}
